-- Generated by lampe

import «rootpackage-0.0.0».Extracted.Dependencies.«package2-0.0.0».GeneratedTypes
import «rootpackage-0.0.0».Extracted.Dependencies.«package2-0.0.0».Lib

namespace «rootpackage-0.0.0»
namespace Extracted
namespace Dependencies
namespace «package2-0.0.0»

def env := «rootpackage-0.0.0».Extracted.Dependencies.«package2-0.0.0».Lib.env
