-- Generated by lampe

import Lampe

open Lampe

namespace «rootpackage-0.0.0»
namespace Extracted
namespace Dependencies
namespace «package4-0.0.0»

noir_struct_def StructFour<> {
  Field,
}

noir_type_alias TypeFour<> := Field;

noir_trait_def TraitFour<> [] := {
  method method_four<>(Self) -> Field;
}

