-- Generated by lampe

import «rootpackage-0.0.0».Extracted.Dependencies.«package4-0.0.0».GeneratedTypes
import Lampe

open Lampe

namespace «rootpackage-0.0.0»
namespace Extracted
namespace Dependencies
namespace «package4-0.0.0»

noir_trait_impl[impl_430]<> TraitFour<> for StructFour<> where [] := {
  noir_def method_four<>(self: StructFour<>) -> Field := {
    self.0
  };
}

noir_def function_four<>(input: Field) -> StructFour<> := {
  (#_makeData returning StructFour<>)(input)
}

def Lib.env : Env := Env.mk
  [function_four]
  [impl_430]
