-- Generated by lampe

import Lampe

open Lampe

namespace «rootpackage-0.0.0»
namespace Extracted
namespace Dependencies
namespace «package2-0.0.0»

noir_struct_def StructTwo<> {
  Field,
}

noir_type_alias TypeTwo<> := Field;

noir_trait_def TraitTwo<> [] := {
  method method_two<>(Self) -> Field;
}

