-- Generated by lampe

import «rootpackage-0.0.0».Extracted.Dependencies.«package2-0.0.0».GeneratedTypes
import Lampe

open Lampe

namespace «rootpackage-0.0.0»
namespace Extracted
namespace Dependencies
namespace «package2-0.0.0»

noir_trait_impl[impl_430]<> TraitTwo<> for StructTwo<> where [] := {
  noir_def method_two<>(self: StructTwo<>) -> Field := {
    self.0
  };
}

noir_def function_two<>(input: Field) -> StructTwo<> := {
  (#_makeData returning StructTwo<>)(input)
}

def Lib.env : Env := Env.mk
  [function_two]
  [impl_430]
