-- Generated by lampe

import Lampe

open Lampe

namespace «package3-0.0.0»
namespace Extracted

noir_struct_def StructThree<> {
  Field,
}

noir_type_alias TypeThree<> := Field;

noir_trait_def TraitThree<> [] := {
  method method_three<>(Self) -> Field;
}

