-- Generated by lampe

import Lampe

open Lampe

noir_struct_def «package3-0.0.0»::StructThree<> {
  Field,
}

noir_type_alias «package3-0.0.0»::TypeThree<> := Field;

noir_trait_def «package3-0.0.0»::TraitThree<> [] := {
  method method_three<>(Self) -> Field;
}

