-- Generated by lampe

import «package3-0.0.0».Extracted.GeneratedTypes
import Lampe

open Lampe

noir_trait_impl[impl_430]<> «package3-0.0.0»::TraitThree<> for «package3-0.0.0»::StructThree<> where [] := {
  noir_def method_three<>(self: «package3-0.0.0»::StructThree<>) -> Field := {
    self.0
  };
}

noir_def «package3-0.0.0»::function_three<>(input: Field) -> «package3-0.0.0»::StructThree<> := {
  (#_makeData returning «package3-0.0.0»::StructThree<>)(input)
}

def Lib.env : Env := Env.mk
  [«package3-0.0.0::function_three»]
  [impl_430]
