-- Generated by lampe

import «package3-0.0.0».Extracted.GeneratedTypes
import Lampe

open Lampe

namespace «package3-0.0.0»
namespace Extracted

noir_trait_impl[impl_430]<> TraitThree<> for StructThree<> where [] := {
  noir_def method_three<>(self: StructThree<>) -> Field := {
    self.0
  };
}

noir_def function_three<>(input: Field) -> StructThree<> := {
  (#_makeData returning StructThree<>)(input)
}

def Lib.env : Env := Env.mk
  [function_three]
  [impl_430]
