-- Generated by lampe

import «package3-0.0.0».Extracted.GeneratedTypes
import «package3-0.0.0».Extracted.Lib

namespace «package3-0.0.0»
namespace Extracted

def env := «package3-0.0.0».Extracted.Lib.env
