-- Generated by lampe

import «package2-0.0.0».Extracted.GeneratedTypes
import «package4-0.0.0».Extracted.GeneratedTypes
import «package1-0.0.0».Extracted.GeneratedTypes
import «package3-0.0.0».Extracted.GeneratedTypes
import Lampe

open Lampe

