-- Generated by lampe

import Lampe
import «std-1.0.0-beta.11».Extracted.GeneratedTypes
import «package1-0.0.0».Extracted.GeneratedTypes -- remote w/ lampe
import «rootpackage-0.0.0».Extracted.Dependencies.«package2-0.0.0».GeneratedTypes -- remote w/o lampe
import «package3-0.0.0».Extracted.GeneratedTypes -- local w/ lampe
import «rootpackage-0.0.0».Extracted.Dependencies.«package4-0.0.0».GeneratedTypes -- local w/o lampe


open Lampe

namespace «rootpackage-0.0.0»
namespace Extracted

