-- Generated by lampe

import «rootpackage-0.0.0».Extracted.GeneratedTypes
import «rootpackage-0.0.0».Extracted.Main

namespace «rootpackage-0.0.0»
namespace Extracted

def env := «rootpackage-0.0.0».Extracted.Main.env
