-- Generated by lampe

import «rootpackage-0.0.0».Extracted.GeneratedTypes
import «rootpackage-0.0.0».Extracted.Main
import «package1-0.0.0».Extracted
import «package2-0.0.0».Extracted
import «package3-0.0.0».Extracted
import «package4-0.0.0».Extracted

namespace «rootpackage-0.0.0»

def env := Main.env
  ++ «package1-0.0.0».env
  ++ «package3-0.0.0».env
  ++ «package2-0.0.0».env
  ++ «package4-0.0.0».env
