-- Generated by lampe

import «rootpackage-0.0.0».Extracted.«rootpackage-0.0.0»
import «rootpackage-0.0.0».Extracted.Dependencies.«package2-0.0.0»
import «rootpackage-0.0.0».Extracted.Dependencies.«package4-0.0.0»
